# version format
version: 1.0.{build}

branches:
  # whitelist
  only:
    - master
    
install:
  - set QTDIR=C:\Qt\5.11.3\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin
  - git submodule update --init --recursive
build_script:
  - cd example\QT_IDE
  - qmake QT_TestProject.pro
  - mingw32-make
