# version format
version: 1.0.{build}

branches:
  # whitelist
  only:
    - master
    
install:
  - set QTDIR=C:\Qt\5.12.2\mingw73_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - cd example\QT_IDE
  - qmake QT_TestProject.pro
  - mingw32-make
