# version format
version: 1.0.{build}

branches:
  # whitelist
  only:
    - master
    
install:
  - set QTDIR=C:\Qt\5.12.2\mingw73_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1
  - git submodule update --init --recursive
build_script:
  - cd example\QT_IDE
  - qmake QT_TestProject.pro
  - mingw32-make
